db:
  username: PROD
  password: jk123!.f
spring:
  datasource:
    username: admin
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    url: jdbc:postgresql://prod:5432/companies
    password: udemy
